profile: dev7
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
      hostname: localhost
spring:
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest